"""Stage and compare the managed files of an authenticated release tree."""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

# Persistent deployment identity; changing the GitHub owner must not invalidate installed markers.
APPLICATION = "cepeter/SillyTavern-Telegram-Bridge"
CANONICAL_REPOSITORY = "cepeter-job/SillyTavern-Telegram-Bridge"
MARKER = ".bridge-deployment.json"
_ROOT_FILES = ("sillytavern_telegram_bridge.py", "CHANGELOG.md", "requirements.lock")


def prepare_payload(release: Path, destination: Path, commit: str, version: str) -> None:
    destination.mkdir(mode=0o700)
    shutil.copytree(release / "bridge", destination / "bridge")
    for name in _ROOT_FILES:
        shutil.copy2(release / name, destination / name)
    (destination / MARKER).write_text(
        json.dumps(
            {"application": APPLICATION, "format": 1, "commit": commit, "version": version},
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def _same_file(expected: Path, actual: Path) -> bool:
    if actual.is_symlink() or not actual.is_file() or expected.stat().st_size != actual.stat().st_size:
        return False
    with expected.open("rb") as source, actual.open("rb") as installed:
        return hashlib.file_digest(source, "sha256").digest() == hashlib.file_digest(installed, "sha256").digest()


def live_matches_release(live: Path, release: Path, version: str, commit: str) -> bool:
    """Match signed managed source and assets, excluding generated bytecode caches.

    Only the deployed root files and bridge tree belong to the managed payload.
    Unrelated root notes do not request repair; replacements retain the old tree
    through the updater's existing backup/activation path.
    """
    try:
        data = json.loads((live / MARKER).read_text(encoding="utf-8"))
        if not (
            isinstance(data, dict)
            and data.get("application") == APPLICATION
            and data.get("format") == 1
            and data.get("version") == version
            and data.get("commit") == commit
        ):
            return False
        # The authenticated archive has already passed the bounded-entry check.
        expected = {Path("bridge"): release / "bridge"}
        expected.update({Path(name): release / name for name in _ROOT_FILES})
        expected.update(
            (path.relative_to(release), path)
            for path in (release / "bridge").rglob("*")
            if "__pycache__" not in path.relative_to(release).parts
        )
        for path in (live / "bridge").rglob("*"):
            relative = path.relative_to(live)
            if "__pycache__" not in relative.parts and relative not in expected:
                return False
        for relative, source in expected.items():
            installed = live / relative
            if source.is_dir():
                if installed.is_symlink() or not installed.is_dir():
                    return False
            elif not _same_file(source, installed):
                return False
    except (OSError, ValueError):
        return False
    return True
